hd_user:
    resource: "@HDUserBundle/Resources/config/routing.yml"
    prefix:   /

amz_upload:
    resource: "@AMZUploadBundle/Resources/config/routing.yml"
    prefix:   /

amz_product:
    resource: "@AMZProductBundle/Resources/config/routing.yml"
    prefix:   /

